Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -45,9 +45,4 @@ jobs:
           TABLE_NAME: ${{ secrets.TABLE_NAME }}
           CODE_NAME: ${{ secrets.CODE_NAME }}
         run: |
-          echo ${#AWS_SECRET_ACCESS_KEY}
-          docker run -d --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-                        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-                        --env REGION=$REGION --env TABLE_NAME=$TABLE_NAME \
-                        --env CODE_NAME=$CODE_NAME \
-                        -p 8000:8000 devops-challenge:latest || { echo "docker run failed ; exit 1 ; }
+          docker run -d --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --env REGION=$REGION --env TABLE_NAME=$TABLE_NAME --env CODE_NAME=$CODE_NAME -p 8000:8000 devops-challenge:latest || { echo "docker run failed ; exit 1 ; }
